name: dart_html5_example1
version: 0.0.1
author: Richard Griffith <scribe.griff@gmail.com>
description: Using the HTML5 <input> range Attribute with the Timer Class in Dart
homepage: http://www.scribegriff.com/studios/index.php?post/2011/12/28/Using-the-HTML5-input-range-Attribute-with-setInterval-in-Dart
dependencies:
  browser: any